package com.pnow.weatheractivityplanner.domain.model

enum class ActivitiesRankingReason {
    SKIING_SNOW_AND_FREEZING,
    SKIING_FREEZING_ONLY,
    SKIING_SNOW_ONLY,
    SKIING_RAIN,
    SKIING_NONE,

    SURFING_THUNDERSTORM,
    SURFING_RAIN,
    SURFING_WARM_AND_WINDY,
    SURFING_WINDY_ONLY,
    SURFING_WARM_ONLY,
    SURFING_NONE,

    OUTDOOR_CLEAR_AND_COMFORTABLE,
    OUTDOOR_RAIN,
    OUTDOOR_FOG,
    OUTDOOR_CLEAR_ONLY,
    OUTDOOR_NONE,

    INDOOR_POOR_OUTDOOR,
    INDOOR_EXTREME_TEMP,
    INDOOR_GREAT_OUTDOOR,
    INDOOR_NONE,

    CYCLING_RAIN,
    CYCLING_GUSTY,
    CYCLING_COMFORTABLE,
    CYCLING_COLD,
    CYCLING_NONE,

    BEACH_DAY_RAIN,
    BEACH_DAY_WINDY,
    BEACH_DAY_WARM_AND_SUNNY,
    BEACH_DAY_SUNNY_ONLY,
    BEACH_DAY_WARM_ONLY,
    BEACH_DAY_NONE,

    STARGAZING_RAIN,
    STARGAZING_FOG,
    STARGAZING_CLEAR_AND_LONG_NIGHT,
    STARGAZING_CLEAR_ONLY,
    STARGAZING_LONG_NIGHT_ONLY,
    STARGAZING_NONE,

    FISHING_THUNDERSTORM,
    FISHING_WINDY,
    FISHING_CALM_AND_DRY,
    FISHING_CALM_ONLY,
    FISHING_DRY_ONLY,
    FISHING_NONE,
}
