package com.pnow.weatheractivityplanner.domain.model

enum class ActivitiesRankingReason {
    SKIING_SNOW_AND_FREEZING,
    SKIING_FREEZING_ONLY,
    SKIING_SNOW_ONLY,
    SKIING_RAIN,
    SKIING_NONE,

    SURFING_THUNDERSTORM,
    SURFING_RAIN,
    SURFING_WARM_AND_WINDY,
    SURFING_WINDY_ONLY,
    SURFING_WARM_ONLY,
    SURFING_NONE,

    OUTDOOR_CLEAR_AND_COMFORTABLE,
    OUTDOOR_RAIN,
    OUTDOOR_FOG,
    OUTDOOR_CLEAR_ONLY,
    OUTDOOR_NONE,

    INDOOR_POOR_OUTDOOR,
    INDOOR_EXTREME_TEMP,
    INDOOR_GREAT_OUTDOOR,
    INDOOR_NONE,
}
